// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: table.proto

package fileHandler.protocolBuffer;

public final class TableProto {
  private TableProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface TableOrBuilder extends
      // @@protoc_insertion_point(interface_extends:protocolBuffer.Table)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required string tablename = 1;</code>
     */
    boolean hasTablename();
    /**
     * <code>required string tablename = 1;</code>
     */
    java.lang.String getTablename();
    /**
     * <code>required string tablename = 1;</code>
     */
    com.google.protobuf.ByteString
        getTablenameBytes();

    /**
     * <code>repeated .protocolBuffer.Column col = 2;</code>
     */
    java.util.List<fileHandler.protocolBuffer.TableProto.Column>
        getColList();
    /**
     * <code>repeated .protocolBuffer.Column col = 2;</code>
     */
    fileHandler.protocolBuffer.TableProto.Column getCol(int index);
    /**
     * <code>repeated .protocolBuffer.Column col = 2;</code>
     */
    int getColCount();
    /**
     * <code>repeated .protocolBuffer.Column col = 2;</code>
     */
    java.util.List<? extends fileHandler.protocolBuffer.TableProto.ColumnOrBuilder>
        getColOrBuilderList();
    /**
     * <code>repeated .protocolBuffer.Column col = 2;</code>
     */
    fileHandler.protocolBuffer.TableProto.ColumnOrBuilder getColOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code protocolBuffer.Table}
   */
  public  static final class Table extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:protocolBuffer.Table)
      TableOrBuilder {
    // Use Table.newBuilder() to construct.
    private Table(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Table() {
      tablename_ = "";
      col_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Table(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              tablename_ = bs;
              break;
            }
            case 18: {
              if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
                col_ = new java.util.ArrayList<fileHandler.protocolBuffer.TableProto.Column>();
                mutable_bitField0_ |= 0x00000002;
              }
              col_.add(
                  input.readMessage(fileHandler.protocolBuffer.TableProto.Column.PARSER, extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
          col_ = java.util.Collections.unmodifiableList(col_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return fileHandler.protocolBuffer.TableProto.internal_static_protocolBuffer_Table_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return fileHandler.protocolBuffer.TableProto.internal_static_protocolBuffer_Table_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              fileHandler.protocolBuffer.TableProto.Table.class, fileHandler.protocolBuffer.TableProto.Table.Builder.class);
    }

    private int bitField0_;
    public static final int TABLENAME_FIELD_NUMBER = 1;
    private volatile java.lang.Object tablename_;
    /**
     * <code>required string tablename = 1;</code>
     */
    public boolean hasTablename() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string tablename = 1;</code>
     */
    public java.lang.String getTablename() {
      java.lang.Object ref = tablename_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          tablename_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string tablename = 1;</code>
     */
    public com.google.protobuf.ByteString
        getTablenameBytes() {
      java.lang.Object ref = tablename_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        tablename_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int COL_FIELD_NUMBER = 2;
    private java.util.List<fileHandler.protocolBuffer.TableProto.Column> col_;
    /**
     * <code>repeated .protocolBuffer.Column col = 2;</code>
     */
    public java.util.List<fileHandler.protocolBuffer.TableProto.Column> getColList() {
      return col_;
    }
    /**
     * <code>repeated .protocolBuffer.Column col = 2;</code>
     */
    public java.util.List<? extends fileHandler.protocolBuffer.TableProto.ColumnOrBuilder>
        getColOrBuilderList() {
      return col_;
    }
    /**
     * <code>repeated .protocolBuffer.Column col = 2;</code>
     */
    public int getColCount() {
      return col_.size();
    }
    /**
     * <code>repeated .protocolBuffer.Column col = 2;</code>
     */
    public fileHandler.protocolBuffer.TableProto.Column getCol(int index) {
      return col_.get(index);
    }
    /**
     * <code>repeated .protocolBuffer.Column col = 2;</code>
     */
    public fileHandler.protocolBuffer.TableProto.ColumnOrBuilder getColOrBuilder(
        int index) {
      return col_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasTablename()) {
        memoizedIsInitialized = 0;
        return false;
      }
      for (int i = 0; i < getColCount(); i++) {
        if (!getCol(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, tablename_);
      }
      for (int i = 0; i < col_.size(); i++) {
        output.writeMessage(2, col_.get(i));
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, tablename_);
      }
      for (int i = 0; i < col_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, col_.get(i));
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof fileHandler.protocolBuffer.TableProto.Table)) {
        return super.equals(obj);
      }
      fileHandler.protocolBuffer.TableProto.Table other = (fileHandler.protocolBuffer.TableProto.Table) obj;

      boolean result = true;
      result = result && (hasTablename() == other.hasTablename());
      if (hasTablename()) {
        result = result && getTablename()
            .equals(other.getTablename());
      }
      result = result && getColList()
          .equals(other.getColList());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      if (hasTablename()) {
        hash = (37 * hash) + TABLENAME_FIELD_NUMBER;
        hash = (53 * hash) + getTablename().hashCode();
      }
      if (getColCount() > 0) {
        hash = (37 * hash) + COL_FIELD_NUMBER;
        hash = (53 * hash) + getColList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static fileHandler.protocolBuffer.TableProto.Table parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static fileHandler.protocolBuffer.TableProto.Table parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static fileHandler.protocolBuffer.TableProto.Table parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static fileHandler.protocolBuffer.TableProto.Table parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static fileHandler.protocolBuffer.TableProto.Table parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static fileHandler.protocolBuffer.TableProto.Table parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static fileHandler.protocolBuffer.TableProto.Table parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static fileHandler.protocolBuffer.TableProto.Table parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static fileHandler.protocolBuffer.TableProto.Table parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static fileHandler.protocolBuffer.TableProto.Table parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(fileHandler.protocolBuffer.TableProto.Table prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code protocolBuffer.Table}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:protocolBuffer.Table)
        fileHandler.protocolBuffer.TableProto.TableOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return fileHandler.protocolBuffer.TableProto.internal_static_protocolBuffer_Table_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return fileHandler.protocolBuffer.TableProto.internal_static_protocolBuffer_Table_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                fileHandler.protocolBuffer.TableProto.Table.class, fileHandler.protocolBuffer.TableProto.Table.Builder.class);
      }

      // Construct using eg.edu.alexu.csd.oop.jdbc.fileHandler.protocolBuffer.TableProto.Table.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getColFieldBuilder();
        }
      }
      public Builder clear() {
        super.clear();
        tablename_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        if (colBuilder_ == null) {
          col_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
        } else {
          colBuilder_.clear();
        }
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return fileHandler.protocolBuffer.TableProto.internal_static_protocolBuffer_Table_descriptor;
      }

      public fileHandler.protocolBuffer.TableProto.Table getDefaultInstanceForType() {
        return fileHandler.protocolBuffer.TableProto.Table.getDefaultInstance();
      }

      public fileHandler.protocolBuffer.TableProto.Table build() {
        fileHandler.protocolBuffer.TableProto.Table result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public fileHandler.protocolBuffer.TableProto.Table buildPartial() {
        fileHandler.protocolBuffer.TableProto.Table result = new fileHandler.protocolBuffer.TableProto.Table(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.tablename_ = tablename_;
        if (colBuilder_ == null) {
          if (((bitField0_ & 0x00000002) == 0x00000002)) {
            col_ = java.util.Collections.unmodifiableList(col_);
            bitField0_ = (bitField0_ & ~0x00000002);
          }
          result.col_ = col_;
        } else {
          result.col_ = colBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof fileHandler.protocolBuffer.TableProto.Table) {
          return mergeFrom((fileHandler.protocolBuffer.TableProto.Table)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(fileHandler.protocolBuffer.TableProto.Table other) {
        if (other == fileHandler.protocolBuffer.TableProto.Table.getDefaultInstance()) return this;
        if (other.hasTablename()) {
          bitField0_ |= 0x00000001;
          tablename_ = other.tablename_;
          onChanged();
        }
        if (colBuilder_ == null) {
          if (!other.col_.isEmpty()) {
            if (col_.isEmpty()) {
              col_ = other.col_;
              bitField0_ = (bitField0_ & ~0x00000002);
            } else {
              ensureColIsMutable();
              col_.addAll(other.col_);
            }
            onChanged();
          }
        } else {
          if (!other.col_.isEmpty()) {
            if (colBuilder_.isEmpty()) {
              colBuilder_.dispose();
              colBuilder_ = null;
              col_ = other.col_;
              bitField0_ = (bitField0_ & ~0x00000002);
              colBuilder_ =
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getColFieldBuilder() : null;
            } else {
              colBuilder_.addAllMessages(other.col_);
            }
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        if (!hasTablename()) {
          return false;
        }
        for (int i = 0; i < getColCount(); i++) {
          if (!getCol(i).isInitialized()) {
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        fileHandler.protocolBuffer.TableProto.Table parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (fileHandler.protocolBuffer.TableProto.Table) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object tablename_ = "";
      /**
       * <code>required string tablename = 1;</code>
       */
      public boolean hasTablename() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string tablename = 1;</code>
       */
      public java.lang.String getTablename() {
        java.lang.Object ref = tablename_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            tablename_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string tablename = 1;</code>
       */
      public com.google.protobuf.ByteString
          getTablenameBytes() {
        java.lang.Object ref = tablename_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b =
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          tablename_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string tablename = 1;</code>
       */
      public Builder setTablename(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        tablename_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string tablename = 1;</code>
       */
      public Builder clearTablename() {
        bitField0_ = (bitField0_ & ~0x00000001);
        tablename_ = getDefaultInstance().getTablename();
        onChanged();
        return this;
      }
      /**
       * <code>required string tablename = 1;</code>
       */
      public Builder setTablenameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        tablename_ = value;
        onChanged();
        return this;
      }

      private java.util.List<fileHandler.protocolBuffer.TableProto.Column> col_ =
        java.util.Collections.emptyList();
      private void ensureColIsMutable() {
        if (!((bitField0_ & 0x00000002) == 0x00000002)) {
          col_ = new java.util.ArrayList<fileHandler.protocolBuffer.TableProto.Column>(col_);
          bitField0_ |= 0x00000002;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          fileHandler.protocolBuffer.TableProto.Column, fileHandler.protocolBuffer.TableProto.Column.Builder, fileHandler.protocolBuffer.TableProto.ColumnOrBuilder> colBuilder_;

      /**
       * <code>repeated .protocolBuffer.Column col = 2;</code>
       */
      public java.util.List<fileHandler.protocolBuffer.TableProto.Column> getColList() {
        if (colBuilder_ == null) {
          return java.util.Collections.unmodifiableList(col_);
        } else {
          return colBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .protocolBuffer.Column col = 2;</code>
       */
      public int getColCount() {
        if (colBuilder_ == null) {
          return col_.size();
        } else {
          return colBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .protocolBuffer.Column col = 2;</code>
       */
      public fileHandler.protocolBuffer.TableProto.Column getCol(int index) {
        if (colBuilder_ == null) {
          return col_.get(index);
        } else {
          return colBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .protocolBuffer.Column col = 2;</code>
       */
      public Builder setCol(
          int index, fileHandler.protocolBuffer.TableProto.Column value) {
        if (colBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureColIsMutable();
          col_.set(index, value);
          onChanged();
        } else {
          colBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .protocolBuffer.Column col = 2;</code>
       */
      public Builder setCol(
          int index, fileHandler.protocolBuffer.TableProto.Column.Builder builderForValue) {
        if (colBuilder_ == null) {
          ensureColIsMutable();
          col_.set(index, builderForValue.build());
          onChanged();
        } else {
          colBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .protocolBuffer.Column col = 2;</code>
       */
      public Builder addCol(fileHandler.protocolBuffer.TableProto.Column value) {
        if (colBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureColIsMutable();
          col_.add(value);
          onChanged();
        } else {
          colBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .protocolBuffer.Column col = 2;</code>
       */
      public Builder addCol(
          int index, fileHandler.protocolBuffer.TableProto.Column value) {
        if (colBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureColIsMutable();
          col_.add(index, value);
          onChanged();
        } else {
          colBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .protocolBuffer.Column col = 2;</code>
       */
      public Builder addCol(
          fileHandler.protocolBuffer.TableProto.Column.Builder builderForValue) {
        if (colBuilder_ == null) {
          ensureColIsMutable();
          col_.add(builderForValue.build());
          onChanged();
        } else {
          colBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .protocolBuffer.Column col = 2;</code>
       */
      public Builder addCol(
          int index, fileHandler.protocolBuffer.TableProto.Column.Builder builderForValue) {
        if (colBuilder_ == null) {
          ensureColIsMutable();
          col_.add(index, builderForValue.build());
          onChanged();
        } else {
          colBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .protocolBuffer.Column col = 2;</code>
       */
      public Builder addAllCol(
          java.lang.Iterable<? extends fileHandler.protocolBuffer.TableProto.Column> values) {
        if (colBuilder_ == null) {
          ensureColIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, col_);
          onChanged();
        } else {
          colBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .protocolBuffer.Column col = 2;</code>
       */
      public Builder clearCol() {
        if (colBuilder_ == null) {
          col_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
          onChanged();
        } else {
          colBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .protocolBuffer.Column col = 2;</code>
       */
      public Builder removeCol(int index) {
        if (colBuilder_ == null) {
          ensureColIsMutable();
          col_.remove(index);
          onChanged();
        } else {
          colBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .protocolBuffer.Column col = 2;</code>
       */
      public fileHandler.protocolBuffer.TableProto.Column.Builder getColBuilder(
          int index) {
        return getColFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .protocolBuffer.Column col = 2;</code>
       */
      public fileHandler.protocolBuffer.TableProto.ColumnOrBuilder getColOrBuilder(
          int index) {
        if (colBuilder_ == null) {
          return col_.get(index);  } else {
          return colBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .protocolBuffer.Column col = 2;</code>
       */
      public java.util.List<? extends fileHandler.protocolBuffer.TableProto.ColumnOrBuilder>
           getColOrBuilderList() {
        if (colBuilder_ != null) {
          return colBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(col_);
        }
      }
      /**
       * <code>repeated .protocolBuffer.Column col = 2;</code>
       */
      public fileHandler.protocolBuffer.TableProto.Column.Builder addColBuilder() {
        return getColFieldBuilder().addBuilder(
            fileHandler.protocolBuffer.TableProto.Column.getDefaultInstance());
      }
      /**
       * <code>repeated .protocolBuffer.Column col = 2;</code>
       */
      public fileHandler.protocolBuffer.TableProto.Column.Builder addColBuilder(
          int index) {
        return getColFieldBuilder().addBuilder(
            index, fileHandler.protocolBuffer.TableProto.Column.getDefaultInstance());
      }
      /**
       * <code>repeated .protocolBuffer.Column col = 2;</code>
       */
      public java.util.List<fileHandler.protocolBuffer.TableProto.Column.Builder>
           getColBuilderList() {
        return getColFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          fileHandler.protocolBuffer.TableProto.Column, fileHandler.protocolBuffer.TableProto.Column.Builder, fileHandler.protocolBuffer.TableProto.ColumnOrBuilder>
          getColFieldBuilder() {
        if (colBuilder_ == null) {
          colBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              fileHandler.protocolBuffer.TableProto.Column, fileHandler.protocolBuffer.TableProto.Column.Builder, fileHandler.protocolBuffer.TableProto.ColumnOrBuilder>(
                  col_,
                  ((bitField0_ & 0x00000002) == 0x00000002),
                  getParentForChildren(),
                  isClean());
          col_ = null;
        }
        return colBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:protocolBuffer.Table)
    }

    // @@protoc_insertion_point(class_scope:protocolBuffer.Table)
    private static final fileHandler.protocolBuffer.TableProto.Table DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new fileHandler.protocolBuffer.TableProto.Table();
    }

    public static fileHandler.protocolBuffer.TableProto.Table getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<Table>
        PARSER = new com.google.protobuf.AbstractParser<Table>() {
      public Table parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new Table(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Table> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Table> getParserForType() {
      return PARSER;
    }

    public fileHandler.protocolBuffer.TableProto.Table getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface ColumnOrBuilder extends
      // @@protoc_insertion_point(interface_extends:protocolBuffer.Column)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required string colname = 1;</code>
     */
    boolean hasColname();
    /**
     * <code>required string colname = 1;</code>
     */
    java.lang.String getColname();
    /**
     * <code>required string colname = 1;</code>
     */
    com.google.protobuf.ByteString
        getColnameBytes();

    /**
     * <code>required string coltype = 2;</code>
     */
    boolean hasColtype();
    /**
     * <code>required string coltype = 2;</code>
     */
    java.lang.String getColtype();
    /**
     * <code>required string coltype = 2;</code>
     */
    com.google.protobuf.ByteString
        getColtypeBytes();

    /**
     * <code>repeated string values = 3;</code>
     */
    java.util.List<java.lang.String>
        getValuesList();
    /**
     * <code>repeated string values = 3;</code>
     */
    int getValuesCount();
    /**
     * <code>repeated string values = 3;</code>
     */
    java.lang.String getValues(int index);
    /**
     * <code>repeated string values = 3;</code>
     */
    com.google.protobuf.ByteString
        getValuesBytes(int index);
  }
  /**
   * Protobuf type {@code protocolBuffer.Column}
   */
  public  static final class Column extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:protocolBuffer.Column)
      ColumnOrBuilder {
    // Use Column.newBuilder() to construct.
    private Column(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Column() {
      colname_ = "";
      coltype_ = "";
      values_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Column(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              colname_ = bs;
              break;
            }
            case 18: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000002;
              coltype_ = bs;
              break;
            }
            case 26: {
              com.google.protobuf.ByteString bs = input.readBytes();
              if (!((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
                values_ = new com.google.protobuf.LazyStringArrayList();
                mutable_bitField0_ |= 0x00000004;
              }
              values_.add(bs);
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
          values_ = values_.getUnmodifiableView();
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return fileHandler.protocolBuffer.TableProto.internal_static_protocolBuffer_Column_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return fileHandler.protocolBuffer.TableProto.internal_static_protocolBuffer_Column_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              fileHandler.protocolBuffer.TableProto.Column.class, fileHandler.protocolBuffer.TableProto.Column.Builder.class);
    }

    private int bitField0_;
    public static final int COLNAME_FIELD_NUMBER = 1;
    private volatile java.lang.Object colname_;
    /**
     * <code>required string colname = 1;</code>
     */
    public boolean hasColname() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string colname = 1;</code>
     */
    public java.lang.String getColname() {
      java.lang.Object ref = colname_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          colname_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string colname = 1;</code>
     */
    public com.google.protobuf.ByteString
        getColnameBytes() {
      java.lang.Object ref = colname_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        colname_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int COLTYPE_FIELD_NUMBER = 2;
    private volatile java.lang.Object coltype_;
    /**
     * <code>required string coltype = 2;</code>
     */
    public boolean hasColtype() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required string coltype = 2;</code>
     */
    public java.lang.String getColtype() {
      java.lang.Object ref = coltype_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          coltype_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string coltype = 2;</code>
     */
    public com.google.protobuf.ByteString
        getColtypeBytes() {
      java.lang.Object ref = coltype_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        coltype_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int VALUES_FIELD_NUMBER = 3;
    private com.google.protobuf.LazyStringList values_;
    /**
     * <code>repeated string values = 3;</code>
     */
    public com.google.protobuf.ProtocolStringList
        getValuesList() {
      return values_;
    }
    /**
     * <code>repeated string values = 3;</code>
     */
    public int getValuesCount() {
      return values_.size();
    }
    /**
     * <code>repeated string values = 3;</code>
     */
    public java.lang.String getValues(int index) {
      return values_.get(index);
    }
    /**
     * <code>repeated string values = 3;</code>
     */
    public com.google.protobuf.ByteString
        getValuesBytes(int index) {
      return values_.getByteString(index);
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasColname()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasColtype()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, colname_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, coltype_);
      }
      for (int i = 0; i < values_.size(); i++) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, values_.getRaw(i));
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, colname_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, coltype_);
      }
      {
        int dataSize = 0;
        for (int i = 0; i < values_.size(); i++) {
          dataSize += computeStringSizeNoTag(values_.getRaw(i));
        }
        size += dataSize;
        size += 1 * getValuesList().size();
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof fileHandler.protocolBuffer.TableProto.Column)) {
        return super.equals(obj);
      }
      fileHandler.protocolBuffer.TableProto.Column other = (fileHandler.protocolBuffer.TableProto.Column) obj;

      boolean result = true;
      result = result && (hasColname() == other.hasColname());
      if (hasColname()) {
        result = result && getColname()
            .equals(other.getColname());
      }
      result = result && (hasColtype() == other.hasColtype());
      if (hasColtype()) {
        result = result && getColtype()
            .equals(other.getColtype());
      }
      result = result && getValuesList()
          .equals(other.getValuesList());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      if (hasColname()) {
        hash = (37 * hash) + COLNAME_FIELD_NUMBER;
        hash = (53 * hash) + getColname().hashCode();
      }
      if (hasColtype()) {
        hash = (37 * hash) + COLTYPE_FIELD_NUMBER;
        hash = (53 * hash) + getColtype().hashCode();
      }
      if (getValuesCount() > 0) {
        hash = (37 * hash) + VALUES_FIELD_NUMBER;
        hash = (53 * hash) + getValuesList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static fileHandler.protocolBuffer.TableProto.Column parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static fileHandler.protocolBuffer.TableProto.Column parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static fileHandler.protocolBuffer.TableProto.Column parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static fileHandler.protocolBuffer.TableProto.Column parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static fileHandler.protocolBuffer.TableProto.Column parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static fileHandler.protocolBuffer.TableProto.Column parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static fileHandler.protocolBuffer.TableProto.Column parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static fileHandler.protocolBuffer.TableProto.Column parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static fileHandler.protocolBuffer.TableProto.Column parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static fileHandler.protocolBuffer.TableProto.Column parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(fileHandler.protocolBuffer.TableProto.Column prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code protocolBuffer.Column}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:protocolBuffer.Column)
        fileHandler.protocolBuffer.TableProto.ColumnOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return fileHandler.protocolBuffer.TableProto.internal_static_protocolBuffer_Column_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return fileHandler.protocolBuffer.TableProto.internal_static_protocolBuffer_Column_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                fileHandler.protocolBuffer.TableProto.Column.class, fileHandler.protocolBuffer.TableProto.Column.Builder.class);
      }

      // Construct using eg.edu.alexu.csd.oop.jdbc.fileHandler.protocolBuffer.TableProto.Column.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        colname_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        coltype_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        values_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return fileHandler.protocolBuffer.TableProto.internal_static_protocolBuffer_Column_descriptor;
      }

      public fileHandler.protocolBuffer.TableProto.Column getDefaultInstanceForType() {
        return fileHandler.protocolBuffer.TableProto.Column.getDefaultInstance();
      }

      public fileHandler.protocolBuffer.TableProto.Column build() {
        fileHandler.protocolBuffer.TableProto.Column result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public fileHandler.protocolBuffer.TableProto.Column buildPartial() {
        fileHandler.protocolBuffer.TableProto.Column result = new fileHandler.protocolBuffer.TableProto.Column(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.colname_ = colname_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.coltype_ = coltype_;
        if (((bitField0_ & 0x00000004) == 0x00000004)) {
          values_ = values_.getUnmodifiableView();
          bitField0_ = (bitField0_ & ~0x00000004);
        }
        result.values_ = values_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof fileHandler.protocolBuffer.TableProto.Column) {
          return mergeFrom((fileHandler.protocolBuffer.TableProto.Column)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(fileHandler.protocolBuffer.TableProto.Column other) {
        if (other == fileHandler.protocolBuffer.TableProto.Column.getDefaultInstance()) return this;
        if (other.hasColname()) {
          bitField0_ |= 0x00000001;
          colname_ = other.colname_;
          onChanged();
        }
        if (other.hasColtype()) {
          bitField0_ |= 0x00000002;
          coltype_ = other.coltype_;
          onChanged();
        }
        if (!other.values_.isEmpty()) {
          if (values_.isEmpty()) {
            values_ = other.values_;
            bitField0_ = (bitField0_ & ~0x00000004);
          } else {
            ensureValuesIsMutable();
            values_.addAll(other.values_);
          }
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        if (!hasColname()) {
          return false;
        }
        if (!hasColtype()) {
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        fileHandler.protocolBuffer.TableProto.Column parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (fileHandler.protocolBuffer.TableProto.Column) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object colname_ = "";
      /**
       * <code>required string colname = 1;</code>
       */
      public boolean hasColname() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string colname = 1;</code>
       */
      public java.lang.String getColname() {
        java.lang.Object ref = colname_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            colname_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string colname = 1;</code>
       */
      public com.google.protobuf.ByteString
          getColnameBytes() {
        java.lang.Object ref = colname_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b =
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          colname_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string colname = 1;</code>
       */
      public Builder setColname(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        colname_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string colname = 1;</code>
       */
      public Builder clearColname() {
        bitField0_ = (bitField0_ & ~0x00000001);
        colname_ = getDefaultInstance().getColname();
        onChanged();
        return this;
      }
      /**
       * <code>required string colname = 1;</code>
       */
      public Builder setColnameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        colname_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object coltype_ = "";
      /**
       * <code>required string coltype = 2;</code>
       */
      public boolean hasColtype() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required string coltype = 2;</code>
       */
      public java.lang.String getColtype() {
        java.lang.Object ref = coltype_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            coltype_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string coltype = 2;</code>
       */
      public com.google.protobuf.ByteString
          getColtypeBytes() {
        java.lang.Object ref = coltype_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b =
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          coltype_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string coltype = 2;</code>
       */
      public Builder setColtype(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        coltype_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string coltype = 2;</code>
       */
      public Builder clearColtype() {
        bitField0_ = (bitField0_ & ~0x00000002);
        coltype_ = getDefaultInstance().getColtype();
        onChanged();
        return this;
      }
      /**
       * <code>required string coltype = 2;</code>
       */
      public Builder setColtypeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        coltype_ = value;
        onChanged();
        return this;
      }

      private com.google.protobuf.LazyStringList values_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensureValuesIsMutable() {
        if (!((bitField0_ & 0x00000004) == 0x00000004)) {
          values_ = new com.google.protobuf.LazyStringArrayList(values_);
          bitField0_ |= 0x00000004;
         }
      }
      /**
       * <code>repeated string values = 3;</code>
       */
      public com.google.protobuf.ProtocolStringList
          getValuesList() {
        return values_.getUnmodifiableView();
      }
      /**
       * <code>repeated string values = 3;</code>
       */
      public int getValuesCount() {
        return values_.size();
      }
      /**
       * <code>repeated string values = 3;</code>
       */
      public java.lang.String getValues(int index) {
        return values_.get(index);
      }
      /**
       * <code>repeated string values = 3;</code>
       */
      public com.google.protobuf.ByteString
          getValuesBytes(int index) {
        return values_.getByteString(index);
      }
      /**
       * <code>repeated string values = 3;</code>
       */
      public Builder setValues(
          int index, java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureValuesIsMutable();
        values_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string values = 3;</code>
       */
      public Builder addValues(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureValuesIsMutable();
        values_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string values = 3;</code>
       */
      public Builder addAllValues(
          java.lang.Iterable<java.lang.String> values) {
        ensureValuesIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, values_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string values = 3;</code>
       */
      public Builder clearValues() {
        values_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000004);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string values = 3;</code>
       */
      public Builder addValuesBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureValuesIsMutable();
        values_.add(value);
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:protocolBuffer.Column)
    }

    // @@protoc_insertion_point(class_scope:protocolBuffer.Column)
    private static final fileHandler.protocolBuffer.TableProto.Column DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new fileHandler.protocolBuffer.TableProto.Column();
    }

    public static fileHandler.protocolBuffer.TableProto.Column getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<Column>
        PARSER = new com.google.protobuf.AbstractParser<Column>() {
      public Column parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new Column(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Column> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Column> getParserForType() {
      return PARSER;
    }

    public fileHandler.protocolBuffer.TableProto.Column getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_protocolBuffer_Table_descriptor;
  private static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_protocolBuffer_Table_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_protocolBuffer_Column_descriptor;
  private static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_protocolBuffer_Column_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\013table.proto\022\016protocolBuffer\"?\n\005Table\022\021" +
      "\n\ttablename\030\001 \002(\t\022#\n\003col\030\002 \003(\0132\026.protoco" +
      "lBuffer.Column\":\n\006Column\022\017\n\007colname\030\001 \002(" +
      "\t\022\017\n\007coltype\030\002 \002(\t\022\016\n\006values\030\003 \003(\tB(\n\032fi" +
      "leHandler.protocolBufferB\nTableProto"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_protocolBuffer_Table_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_protocolBuffer_Table_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_protocolBuffer_Table_descriptor,
        new java.lang.String[] { "Tablename", "Col", });
    internal_static_protocolBuffer_Column_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_protocolBuffer_Column_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_protocolBuffer_Column_descriptor,
        new java.lang.String[] { "Colname", "Coltype", "Values", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
